### ISSUE TITLE
Send data with notification

### ISSUE THREAD

**Issue by ferenax** [Alymosul/exponent-server-sdk-php#1]
I am trying to send data with notification on a laravel backend to a react-native expo app. I managed to successfully send a notification, however, I can't seem to be able to send data (or don't know how).

So far here is my implementation :

```
$interestDetails = [$this->userId, $token];

// You can quickly bootup an expo instance
$expo = Expo::normalSetup();

// Subscribe the recipient to the server
$expo->subscribe($interestDetails[0], $interestDetails[1]);

// Build the notification data
$notification = ['body' => 'Hello World!', 'data' => ['message' => 'my message']];

// Notify an interest with a notification
$expo->notify($interestDetails[0], $notification);
```
Is sending data currently supported ? If so, how to send it ?

Thank you,

**Comment by Alymosul** [comment]
The data should be a JSON object and it must be at most 4KiB

**Comment by ferenax** [comment]
Thank you, I successfully managed to send data with notifications.
