### ISSUE TITLE
requires:  php: >=7.0

### ISSUE THREAD

**Issue by tarekbazine** [Alymosul/exponent-server-sdk-php#13]
I do not understand why you requires php7 (there are no deps) ! could  you downgrade to php 5.6 -to support mor hosting-? or let me know if it is possible maybe i could fork it and do it by myself, thanks

**Comment by tarekbazine** [comment]
and please add it to README so people could know about php7

**Comment by Alymosul** [comment]
PHP7 is needed because some functions declare return types which is supported starting from php7

**Comment by terryBaz** [comment]
for those who ask 👌 
I forked the repo and made small changes to support php5 [link to rep](https://github.com/terryBaz/exponent-server-sdk-php)

> how to use it ?

in your `composer.json`
**put**
```
{
   //...
   "require": {
        "alymosul/exponent-server-sdk-php": "dev-master",
        //...
    },
   //....
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/terryBaz/exponent-server-sdk-php"
        }
    ]
}
```
**instead of**
```
{
   //...
   "require": {
        "alymosul/exponent-server-sdk-php": "^1.0",
         //...
    }
}
```

**Comment by tarekbazine** [comment]
for those who ask 👌 
I forked the repo and made small changes to support php5 [link to rep](https://github.com/terryBaz/exponent-server-sdk-php)

> how to use it ?

in your `composer.json`
**put**
```
{
   //...
   "require": {
        "alymosul/exponent-server-sdk-php": "dev-master",
        //...
    },
   //....
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/terryBaz/exponent-server-sdk-php"
        }
    ]
}
```
**instead of**
```
{
   //...
   "require": {
        "alymosul/exponent-server-sdk-php": "^1.0",
         //...
    }
}
```
