### ISSUE TITLE
Multiple Notification send at once 

### ISSUE THREAD

**Issue by Ahmed-Imam** [Alymosul/exponent-server-sdk-php#21]
it sends multiple notifications at once, my code is as follow

```
<?php
   require_once('./vendor/autoload.php');
   require_once('./includes_/mysql_functions.php');


 $msg = 'Aloo';
$key = "ExponentPushToken[OcavxbB6AsB5wr_Ep7Fxhn]";
$title = "title";
  
  try{
      $expo = \ExponentPhpSDK\Expo::normalSetup();
  // Build the notification data
  $notification = ['to' => $key,'title' => $title,'body' => $msg];
  // Notify an interest with a notification
 $expo->notify('https://exp.host/--/api/v2/push/send',$notification);
  	
  $status = 'success';
}catch(Exception $e){
	echo $e;
}
  echo $status;
  ?>
```

**Comment by Koronos** [comment]
I use the next format and works whitout any problem.

``` php
//I use your variables
$expo->subscribe($userId, $key); //$userId from database
$expo->notify($userId,['body'=>$msg]);
```

**Comment by Ahmed-Imam** [comment]
your code works fine but the problem is, it keeps subscribing the user again and again which leads to add one notification every time the user is subscribed, how can i check if the user is already subscribed ? so i can simply send the notification without subscribing.

**Comment by Ahmed-Imam** [comment]
I did fix the problem in catch, I am sending the notification to the userId, if there is an exception which is most probably if the user is unsubscribed, I am subscribing the user and sending the notification. 
it did work for me now, please if there is a better way implementing this, don't hesitate to comment

```
<?php
   require_once('./vendor/autoload.php');
   require_once('./includes_/mysql_functions.php');
 $msg = 'Aloo';
$key = "ExponentPushToken[0GAEokJazChx21MOxeC1l2]";
$title = "title";
$userId = 'userID';
$notification = ['title' => $title,'body' => $msg];
  try{

//Sending the notification without subscribing
      $expo = \ExponentPhpSDK\Expo::normalSetup();
      $expo->notify($userId,$notification);
      $status = 'success';

}catch(Exception $e){

 //if there is an exception Most probably cause the userid is unsubscribed	
        $expo->subscribe($userId, $key); //$userId from database
        $expo->notify($userId,$notification);
        $status = 'new subscription';
}
  echo $status;
  ?>

**Comment by Alymosul** [comment]
You need to subscribe you're user one time only not with every time you're sending notifications.... this duplicate subscription of tokens is fixed in --dev version and will be released soon when we're done writing tests for the package...

**Comment by AleksandarSavic95** [comment]
For anyone asking themselves "why didn't the `1.1.1` fix this issue?" please look at [the issue I opened today](https://github.com/Alymosul/exponent-server-sdk-php/issues/27). Basically, *composer* will not pull the changes made after the release **date** of current version. So, I requested a `v1.1.2` release. I hope that this will fix the issue for good :)
