### ISSUE TITLE
Change the storage folder

### ISSUE THREAD

**Issue by Koronos** [Alymosul/exponent-server-sdk-php#22]
I have a project in Docker, and when I try to register an user with `suscribe`, it throws an error. I find that It throws an error about it cannot find the file `tokens.json` in the vendor folder. 

It seems like is an issue with the permissions, composer generates the vendor folder with readonly permissions (and root as user).

Is possible add a parameter to configure the default folder where is going to be saved the `tokens.json` file?

**Comment by Alymosul** [comment]
Currently you can't configure the tokens.json path, feel free to submit a PR to support this feature.
