### ISSUE TITLE
interests vs recipients?  FailedCompletely called even if most pushes went out ok.

### ISSUE THREAD

**Issue by crazedVic** [Alymosul/exponent-server-sdk-php#23]
I'm not sure what the original purpose of interests was , however I am using it to group a set of push messages together, say for a specific topic or even just by timestamp.  This lets me essentially track the messages sent as a batch.  which works great.  Kinda simulates FCM topics.

```
$timestamp = date(DATE_ATOM);
 foreach ($db->query($sql) as $row) {
        //gather tokens from database and start pushing to expo server
        $expo->subscribe($timestamp, $row['token']);
    }
//send push
  $results = $expo->notify($timestamp, $notification);
 //delete the batch
 $expo->unsubscribe($timestamp);
```
however if i have one invalid push token in my database, it triggers fail completely, which I would think to mean fail completely is if not a single message was delivered.  the code however is assuming that every device has its own interest, which then calls into question, what was interest for? I already have a unique recipient value, namely the expo push token.

```
private function failedCompletely(array $response, array **$interests**)
[..]

```
so instead of getting this:
```
0: {status: "ok", id: "440fec28-0696-4e40-b9c7-4396d06dc578"}
1: {id: "217f6c0c-9109-4445-bddc-cea0059cef53", status: "ok"}
2: {status: "error", message: ""ExponentPushToken[iCWoARH_b_IqDfTnnB7Nmr]" is not a registered push notification recipient"
```

Which i can work with, i get a complete failure exception on this batch, even though the message was indeed successfully sent to valid devices.

To get this working i changed this line in Expo.php:
```
if (!$debug && $this->failedCompletely($response, **$recipients**)) {
            throw ExpoException::failedCompletelyException($response);
        }

```

**Comment by Alymosul** [comment]
Basically an interest is a recipient the way this SDK designed is to notify one recipient (interest) at a time.
