### ISSUE TITLE
Badge clearing not working

### ISSUE THREAD

**Issue by BillyFigueroa** [Alymosul/exponent-server-sdk-php#24]
I am noticing that if I set the badge number to 1, the app will remain on 1 even after the notification is viewed. This seems broken to me

**Comment by Alymosul** [comment]
Hello, This has nothing to do with the SDK you should clear the badge inside your app source code, this package is only for sending notifications via Expo Api.

**Comment by BillyFigueroa** [comment]
Ok, not very helpful and very dismissive response

**Comment by Alymosul** [comment]
I apologize if my reply was harsh but honestly this is not related to this package it should has to do with expo app itself..

**Comment by BillyFigueroa** [comment]
Thank you. I will reach out to expo. No one has been very clear about how this is to be done. If I knew how to do it, I would have done it by now in my own code. I just want some documentation on how to do it because I can't find any

**Comment by vijay2330** [comment]
@BillyFigueroa  any solution regarding clearing the badges?

**Comment by BillyFigueroa** [comment]
@vijay2330 I had to make changes on the front end. In this case it was in my app. When you trigger a notification you have access to an object that has the count. You have to subtract one from the count or set it to zero
