### ISSUE TITLE
Notification sound & badge functionality

### ISSUE THREAD

**Issue by chris-mackie** [Alymosul/exponent-server-sdk-php#25]
Would be great to get sound and badges working on this.

For the time being i have just changed line 103 in Expo.php to this:

`$postData[] = $data + ['to' => $token, 'sound' => 'default', 'badge' => 1];`

Thanks

**Comment by Alymosul** [comment]
You don't need to edit in the Expo.php file, you just pass the sound & badge in the $data.
```
$data = ['sound' => 'default', 'badge' => 1, 'body' => 'your message'];
```
