### ISSUE TITLE
Urgent - Please release version 1.1.2 - composer doesn't update the code

### ISSUE THREAD

**Issue by AleksandarSavic95** [Alymosul/exponent-server-sdk-php#27]
After many days of research and cache invalidation, I am pretty sure that composer will not pull any changes made after the date of version release.
In other words, version `1.1.1` will **not** include the code pushed after the 26th of September (note the **since** word below).
![image](https://user-images.githubusercontent.com/12213798/51467079-f3c52300-1d6b-11e9-948b-2bc0c1d5411f.png)

Therefore, I am asking You to make a release of version `1.1.2`, since that is the only way for me to fix notification bugs in my production environment.
This is **urgent**, so please act quickly :)

Thank You for Your time.

Best regards,
Aleksandar

**Comment by Alymosul** [comment]
v1.1.2 released

**Comment by AleksandarSavic95** [comment]
> v1.1.2 released

Thank You! 😊
