### ISSUE TITLE
TypeError: Argument 1 passed to ExponentPhpSDK\Expo::failedCompletely() must be of the type array

### ISSUE THREAD

**Issue by alexisLefebvre** [Alymosul/exponent-server-sdk-php#36]
We had a type error from this library, I'm pretty sure that is it due to an error from Expo API, maybe when it doesn't respond or respond an error.

Stacktrace of the error:

```
TypeError: Argument 1 passed to ExponentPhpSDK\Expo::failedCompletely() must be of the type array, null given, called in /app/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php on line 113
#18 vendor/alymosul/exponent-server-sdk-php/lib/Expo.php(128): failedCompletely
#17 vendor/alymosul/exponent-server-sdk-php/lib/Expo.php(113): notify
#16 [project's code …]
#1 vendor/symfony/console/Application.php(145): run
#0 bin/console(39): null
```

Line that trigger the error: https://github.com/Alymosul/exponent-server-sdk-php/blob/4c618200c6cd14e15d0918b317f7f956790ef0dc/lib/Expo.php#L113

Code:

```
$response = $this->executeCurl($ch);

// If the notification failed completely, throw an exception with the details
if (!$debug && $this->failedCompletely($response, $interests)) {
    throw ExpoException::failedCompletelyException($response);
}
```

If `$response` is not an array, calling `$this->failedCompletely($response, $interests)` will fail because the first argument must be an array.

We can replicate the bug by changing value of `$response`: `$response = null;`. Then try to send a notification and you will have the same error.

**Comment by alexisLefebvre** [comment]
Type-hint of `executeCurl` show that it always return an array but we had some error where is was `null`.

**Comment by Alymosul** [comment]
Check my comment on #37
