### ISSUE TITLE
The recipient device is not registered with FCM... but only on production server

### ISSUE THREAD

**Issue by philyboysmith** [Alymosul/exponent-server-sdk-php#40]
I'm triyng to send to an android device. Locally, this is working fine, but on my production and staging environment it's failing with the error: The recipient device is not registered with FCM.

It also works fine using the notifications testing tool.

Any ideas?

**Comment by Alymosul** [comment]
I think this error is not related to this package and occurring from Expo API itself. Maybe installing and uninstalling the app will fix it, but i think you should write to expo's support team to help you with that.

**Comment by philyboysmith** [comment]
Expo we’re having issues. I think this is on them.
