### ISSUE TITLE
Empty value

### ISSUE THREAD

**Issue by philyboysmith** [Alymosul/exponent-server-sdk-php#41]
I’m having this issue I. Production. Not sure if it’s to do with the volume of messages i’m Sending.

Any thoughts?

ErrorException: Creating default object from empty value in 
/vendor/alymosul/exponent-server-sdk-php/lib/Repositories/ExpoFileDriver.php:49

**Comment by philyboysmith** [comment]
Okay I've sussed out the issue. tokens.json was pretty big. I deleted it and everything works as normal. When and how does this file get flushed out, I'm sending about 3,000 notifications a day (it's a festival!)

**Comment by Alymosul** [comment]
it does not get flushed it keeps adding, maybe i need to add this option.

**Comment by pauliak1** [comment]
You get this ErrorException when tokens.json is empty

**Comment by Bruno-Meowtel** [comment]
I'm using v1.3.0 and got the same issue today :+1: 

As mentioned by others, renaming or deleting `vendor/alymosul/exponent-server-sdk-php/storage/tokens.json` seems to fix the issue.

@Alymosul, any chance you could implement a flush mechanism every x entries? Thank you for the great work!

**Comment by Alymosul** [comment]
I will not implement flush mechanism, I believe the proper solution would be providing a different more optimized storage like: redis, database,..etc.

**Comment by JamesKindyHub** [comment]
@Alymosul Has there been any development on how these are stored or do we still need to clear out the tokens.json periodically?

**Comment by Alymosul** [comment]
@JamesKindyHub  unfortunately i didn't have enough time to provide a different storage. Feel free to submit that feature via PR ;)
