### ISSUE TITLE
how to set _displayInForeground

### ISSUE THREAD

**Issue by virtualLast** [Alymosul/exponent-server-sdk-php#44]
Hi, I've had a quick run through the source code and read your readme file but I am unsure how to set _displayInForeground

[More detail from Expo.io](https://docs.expo.io/versions/latest/guides/push-notifications/#3-handle-receiving-andor-selecting-the-notification)

**Comment by Alymosul** [comment]
Hello, you can simply add it to the second parameter to the method `notify()`

for example:
```
$notification = ['body' => 'You received a new message!', '_displayInForeground' => true];

$expo->notify($user, $notification);
```
