### ISSUE TITLE
Composer package is not up-to-date

### ISSUE THREAD

**Issue by srosset81** [Alymosul/exponent-server-sdk-php#45]
Hello,

If I do:
```
compose require alymosul/exponent-server-sdk-php:1.1.2
```
Composer works alright and think it has downloaded the version 1.1.2 but in fact it's an older release, probably 1.1.1. We see that by the fact the `setStorage` method is not available, even though it was added on version 1.1.2.

On [packagist](https://packagist.org/packages/alymosul/exponent-server-sdk-php) we see the latest commit is c3fec550e2c0c0e6dea94866a122c93d97915f03. 

I'm assuming it's a problem of branch tagging but I could be wrong.

**Comment by Alymosul** [comment]
yes, that's gonna be in the next version.. i'll publish it in a few days
