### ISSUE TITLE
What are you waiting here:   $interestDetails = ['unique identifier', 'ExponentPushToken[unique]'];

### ISSUE THREAD

**Issue by arilishu** [Alymosul/exponent-server-sdk-php#46]
What do you mean with unique identifier and unique?

my token looks like ExponentPushToken[ABCD]
ABCD is the unique identifier?
Or what am i missing?

**Comment by ghost** [comment]
I have the same doubt, you know what it is?

**Comment by arilishu** [comment]
No...

**Comment by jmmorillon** [comment]
Based on https://github.com/Alymosul/exponent-server-sdk-php/issues/21#issuecomment-432480632 ... it seem's to be your own user ID, to register a user by this ID and the token.
