### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by moay** [Alymosul/exponent-server-sdk-php#51]
Hi there. :-) Thanks for your work, great to have a library for this. Do you have any plans on releasing a new version? When installing with composer, I get 1.1.2, which is now nearly one year old and does not contain some important fixes. Thanks!

**Comment by Alymosul** [comment]
Hey, Yeah i'll release a new version in the coming 2 weeks

**Comment by Derewith** [comment]
Any news? @Alymosul like i want to contribute 👍

**Comment by Alymosul** [comment]
1.2.0 released
