### ISSUE TITLE
Tokens storage file not found

### ISSUE THREAD

**Issue by ghena** [Alymosul/exponent-server-sdk-php#52]
Hi guys, under windows 10 i get this error:

Fatal error: Uncaught Exception: Tokens storage file not found. in \vendor\alymosul\exponent-server-sdk-php\lib\Repositories\ExpoFileDriver.php on line 137

// You can quickly bootup an expo instance
$expo = \ExponentPhpSDK\Expo::normalSetup();

$channelName = 'user_528491';
$recipient = 'ExponentPushToken[xxxx]';
  
//   // Build the notification data
$notification = ['body' => 'Hello World!', 'data'=> json_encode(array('someData' => 'goes here'))];

//   // Notify an interest with a notification
$test= $expo->notify($channelName, $notification);

**Comment by Alymosul** [comment]
You can set a custom storage file path in v1.2.0, that should have the proper permissions.
