### ISSUE TITLE
i am getting this message how to solve it ?

### ISSUE THREAD

**Issue by khurramrashid** [Alymosul/exponent-server-sdk-php#53]
fopen(/var/www/html/app/vendor/alymosul/exponent-server-sdk-php/lib/Repositories/../../storage/tokens.json): failed to open stream: Permission denied

solution of it please.....

**Comment by khurramrashid** [comment]
fixed

**Comment by ghost** [comment]
> fopen(/var/www/html/app/vendor/alymosul/exponent-server-sdk-php/lib/Repositories/../../storage/tokens.json): failed to open stream: Permission denied
> 
> solution of it please.....

What was the solution?

**Comment by ruan-lucas** [comment]
Just give the correct permissions to the vendor folder.
`chmod -R 775 vendor`
