### ISSUE TITLE
Typo in class Expo, in function notify

### ISSUE THREAD

**Issue by andrey-aristov** [Alymosul/exponent-server-sdk-php#56]
The current part of code, that checks whether the sending has completely failed working incorrect. 

Here is this part:   
`if (!$debug && $this->failedCompletely($response, $interests)) {
   throw ExpoException::failedCompletelyException($response);
}`
https://github.com/Alymosul/exponent-server-sdk-php/blob/99a05731e6190b0a156905b1d8593142fde9544c/lib/Expo.php#L111

It must be replace on:
`if (!$debug && $this->failedCompletely($response, $recipients)) {
            throw ExpoException::failedCompletelyException($response);
}`

In fact, the function (`failedCompletely`) is called with the wrong parameter (`$interests`), correct parameter - `$recipients`. Also, local variables in the function (`failedCompletely`) must be renamed. 

Because the main idea of ​​the function (`failedCompletely`) is to compare the total number of recipients with the number of failures to send a notification (and not with the number of interests/channels).

This code gives an exception (indicating that the entire function failed) if the number of failures in the mass sending list matches the number of interests. For example, when sending 50 by the recipient from one interest, one unsuccessful sending from 50 will lead to an exception.

**Comment by Alymosul** [comment]
Thanks! Always feel free to submit a PR with fixes or ideas :)

**Comment by andrey-aristov** [comment]
Hi Alymosul.
This fix was not included in the latest stable release (1.2.0). The corrected code can only be found in the source files.
When updating through the composer, we do not receive the correct code.

**Comment by Alymosul** [comment]
Fix included in latest release (1.3.0)
