### ISSUE TITLE
Urgent - Could not register the token provided for the interest, due to internal error.

### ISSUE THREAD

**Issue by sandun86** [Alymosul/exponent-server-sdk-php#6]
Hi,
I have got following error. Can you please explain why is it ?

`"Could not register the token provided for the interest, due to internal error."`

And I have check the `ExpoFileDriver.php` file. So there has a variable called 
`private $storage = __DIR__.'/../../storage/tokens.json';`

I have checked that `storage` folder and but I can not see any `tokens.json` file. Why is it ?

**Comment by Alymosul** [comment]
The tokens.json file is created on the first attempt to subscribe a user. try creating the file manually and see if it passes.

**Comment by sandun86** [comment]
There was a issue with my php version too. I have deployed it into php7 server. Then it has automatically fixed.

**Comment by scchess** [comment]
I got the same problem too, but I think my PHP server is working well. Not sure what `tokens.json` we're talking about. Where should I create it?

My token ID was working with Expo's provided notification tool, but when I used the code on README, I got the this error message.

**Comment by NERDGHOST** [comment]
Modifying File Permissions for vendor directory to a more permissive setting fixed for me.
