### ISSUE TITLE
I can't understand why giving this

### ISSUE THREAD

**Issue by swipe13** [Alymosul/exponent-server-sdk-php#65]
my code sends notifications only that it gives me an error at the end and I can't understand why someone can explain it to me?

`Fatal error: Uncaught ExponentPhpSDK\Exceptions\ExpoException: "ExponentPushToken[unique]" is not a registered push notification recipient in C:\xampp\htdocs\teste\login\vendor\alymosul\exponent-server-sdk-php\lib\Exceptions\ExpoException.php:24 Stack trace: #0 C:\xampp\htdocs\teste\login\vendor\alymosul\exponent-server-sdk-php\lib\Expo.php(116): ExponentPhpSDK\Exceptions\ExpoException::failedCompletelyException(Array) #1 C:\xampp\htdocs\teste\login\index.php(24): ExponentPhpSDK\Expo->notify(Array, Array) #2 {main} thrown in C:\xampp\htdocs\teste\login\vendor\alymosul\exponent-server-sdk-php\lib\Exceptions\ExpoException.php on line 24`

if you can help me, I would be very grateful!

**Comment by liorokach** [comment]
hi,
make sure that you used the command: `composer require alymosul/exponent-server-sdk-php` inside your root directory.
hope that helps!

**Comment by josephajibodu** [comment]
The device `ExponentPushToken[unique]` cannot receive push notifications anymore and you should stop sending messages to the corresponding Expo push token.

**The best you can do is unsubscribe such recipient from any channel they are subscribed to.**

`$expo->unSubscribe($channelName, $recipient);`

So write your code to catch ExpoException when sending notifications.

```php
try {
    $response = $expo->notify([$channelName], $notification);
} catch (ExpoException $e) {
    // You can log the error first
    // loop over the $response for those that have  "status" == "error"
        // extract the ExpoId and unsubscribe the ExpoId
}
```

**Comment by swipe13** [comment]
thank you for help me !!
