### ISSUE TITLE
Storage tokens file for multiple app servers

### ISSUE THREAD

**Issue by ctwillie** [Alymosul/exponent-server-sdk-php#69]
We are currently using this package and have three app servers behind a load balancer. I did some source diving here and noticed the expo push tokens are stored in a local file (storage/tokens.json). I believe this can be problematic with multiple app servers as each app server will have different token subscriptions based on where the load balancer directs traffic. 

I don't believe this package handles situations where there are multiple app servers. Any insights?

Thanks!

**Comment by joearcher** [comment]
We've also run into an issue with the token storage location, as it is in the vendor folder the permissions are often reset when we perform package updates, leaving the token file read only. It doesn't make much sense having a writable file located in the vendor folder to me. I may submit a PR when I get chance which will add a constructor to the `ExpoFileDriver` class to allow a file path to be passed in on instantiation. This may not help your situation though @ctwillie, unless your app servers share a filesystem of some kind.

**Comment by Alymosul** [comment]
Hey @ctwillie 👋  the package doesn't handle this but recently I got multiple issues with the local file therefore I'm thinking that we need to provide either a custom file path for the tokens file or a different storage like db, redis, ..etc. Tbh i'm kinda busy at the moment with some private work but we'll appreciate it if anyone can submit a PR with any of the two solutions :)

**Comment by ctwillie** [comment]
@Alymosul I plan on spending time to help maintain this repo. I will be submitting a PR tomorrow sometime that adds a database driver/repository to solve this issue. The PR will require a new major release as the minimum php version will need to be bumped to 7.3 for a repo I am requiring to read .env files for database credentials. How open are you to major changes to this package?
