### ISSUE TITLE
DeployBot problem

### ISSUE THREAD

**Issue by EduOggioni** [Alymosul/exponent-server-sdk-php#7]
I have a project, using the DeployBot, every deploy in the develop or production, a new dir as created and the project builded in this folder.

The big problem: tokens.json
In any deploy made, a fresh install of the dependecies are made, and i lose my tokens.json.

I'll try do something here and send!

**Comment by Alymosul** [comment]
I think you can extend the ExpoFileDriver and override the $storage property with the path of the json file that will not be modified by the DeployBot...or you can create an ExpoDatabaseDriver, i think i'll be adding this feature very soon.
