### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by ProdigyView** [Alymosul/exponent-server-sdk-php#76]
When I do a request to the api with a token, I got this error:

fopen(/var/www/html/vendor/alymosul/exponent-server-sdk-php/lib/Repositories/../../storage/tokens.json): Failed to open stream: Permission denied

I've a tried changing the permissions and its not working. I'm also on Docker and permissions should not be a problem.

**Comment by ctwillie** [comment]
Try deleting the entire vendor directory, and then running ```composer install```. Seems to be a file permission issue.

**Comment by ProdigyView** [comment]
@ctwillie I've done that and set permissions to 777 inside the docker container.

**Comment by josephajibodu** [comment]
I assume the issue is resolved and can be closed.
