### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by khangdoan03121993** [Alymosul/exponent-server-sdk-php#8]
I installed exponent-server-sdk-php package. I config as the guide. But I got issue 

![untitled](https://user-images.githubusercontent.com/15787361/42141664-af86e34a-7dd4-11e8-895f-f97e9c0d365b.png)

This is the way I config:

![untitled 1](https://user-images.githubusercontent.com/15787361/42141680-c1b6fa1e-7dd4-11e8-80e3-66c85b7a9160.png)

Can you help me? Thanks

**Comment by Alymosul** [comment]
The problem is with the $response which is null, it's blocking the throw of the ExpoException::failedCompletelyException.... I'll fix that in the source code however the failure is not from the package itself..
